### ISSUE TITLE
Project with empty/broken repo link show error

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#47]
Internal error if the GitHub repository field is not correctly set, e.g.
http://www.opensourcebrain.org/projects/abcdef

Possible root of this:

```
 ActionView::Template::Error (undefined method `scm_name' for nil:NilClass):
    93: 						<% category =  getCustomField(@project,"Category")  %>
    94: 						<% isAProject = (category=="Project" or category=="Showcase") %>
    95: 						<% if isAProject %>
    96: 							<% @neuroml2files = getNML2Files(@project.repository) %>
    97: 							<% @swcfiles = getSWCFiles(@project.repository) %>
    98: 							<% @repourl=getHttpRepositoryURL(@project) %>
    99: 							<% @repopath=getHttpRepositoryPath(@project.repository) %>
  app/helpers/application_helper.rb:348:in `getHttpRepositoryPath'
  app/views/layouts/base.html.erb:96:in `_app_views_layouts_base_html_erb___1143358954942024164_50816800'
  app/controllers/projects_controller.rb:406:in `show'
```

**Comment by pgleeson** [comment]
Seems to be fixed...
