### ISSUE TITLE
Test NSG submission

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#55]
Current status of NSG access:

### Live server (~4 months behind development)

NSG submission working correctly here. Note jobs are submitted to [Comet](https://portal.xsede.org/resource-monitor#) and queue is quite busy, but jobs get successfully set running

### Comodl  (~1 month behind development)

NSG submission fails with error at point of sending job (difficult to see precise point due to [lost exception](https://github.com/openworm/org.geppetto.simulator.external/pull/38))

### Local copy of [pg_netpyne branches](https://github.com/OpenSourceBrain/geppetto-osb/issues/49)

Working following https://github.com/openworm/org.geppetto.model.neuroml/issues/128...

### Local copy of development (PG) + [#38](https://github.com/openworm/org.geppetto.simulator.external/pull/38)

To test...

**Comment by tarelli** [comment]
@pgleeson for the local environment without the new NML/LEMS libraries one thing worth checking is that in the repository/usr there are no libraries that are left over from the new NML/LEMS libraries or any of their added dependencies which can cause runtime conflicts even if the currently deployed org.geppetto.neuroml.model doesn't use them.

**Comment by pgleeson** [comment]
@tarelli yep, I do that whenever I switch configuration, see https://github.com/openworm/org.geppetto/issues/543#issuecomment-313642192

**Comment by tarelli** [comment]
So there are no relevant changes on simulator.external, see https://github.com/openworm/org.geppetto.simulator.external/compare/v0.3.5-alpha...development.
What I can think about is the new 1.5.1 brought in some JARs that are causing this conflict 
![screen shot 2017-07-07 at 11 24 34](https://user-images.githubusercontent.com/81127/27954232-f657d502-6306-11e7-847d-65503a06242d.png) [diff](https://github.com/openworm/org.geppetto.model.neuroml/compare/v0.3.5-alpha...development)

**Comment by tarelli** [comment]
@adrianq thanks! (see comment here https://github.com/openworm/org.geppetto.model.neuroml/issues/128#issuecomment-313647810). Definitely worth investigating cc @pgleeson @mattearnshaw This is the commit from Adrian that fixed the problem https://github.com/OpenSourceBrain/NSGPortalShowcase/commit/d5a5facacee1888640a15272fe4ce5c5e2f7d556#diff-ba3dbca405cc1e9ea164f8cf3a03867c is that still in use?

**Comment by pgleeson** [comment]
Updated description based on success following @adrianq tip...

**Comment by pgleeson** [comment]
Finally, finally, I've managed to successfully run parallel jobs (up to 16 processors) on NetPyNE through the OSB interface from my local install. Phew.

The scripts are run successfully on NSG across the required numbers of processors, but it awaits an updated release of NetPyNE (that I've been bugging @salvadord about :-)) before they complete/save results successfully.

**Comment by salvadord** [comment]
fantastic! yup, I'll release before Sunday so ready for NSG/CNS prime time :)

**Comment by pgleeson** [comment]
Thanks, @salvadord!

**Comment by mattearnshaw** [comment]
fwiw I have also tried out the [`pg_netpyne branches`](https://github.com/OpenSourceBrain/geppetto-osb/issues/49) today and got things submitting to NSG without much difficulty (once I had installed all the right python libraries)…

**Comment by pgleeson** [comment]
Working, just needs to be switched to production server  https://nsgr.sdsc.edu:8443 on live & retested

**Comment by mattearnshaw** [comment]
Neuron NSG working on live, NetPyNE fails with `FileNotFoundException` on _results0.dat_:

```
[2017-12-18 13:41:43.162] INFO  Thread-42                    System.out                                                         Mon Dec 18 13:41:16 UTC 2017:SUBMITTED:Submitted to comet as job '13369278'. 
[2017-12-18 13:41:43.162] INFO  Thread-42                    System.out                                                         Mon Dec 18 13:41:42 UTC 2017:LOAD_RESULTS:Trying to transfer results. 
[2017-12-18 13:41:43.162] INFO  Thread-42                    System.out                                                         Mon Dec 18 13:41:42 UTC 2017:COMPLETED:Output files retrieved.  Task is finished. 
[2017-12-18 13:41:45.199] ERROR Thread-42                    org.geppetto.core.recordings.ConvertDATToRecording                java.io.FileNotFoundException: /home/virgo/geppetto/geppettoTmp/RUN/projects/352/584/network_ACnet2/NETPYNEModel_18122017_134057/results/results0.dat (No such file or directory) 
[2017-12-18 13:41:45.200] ERROR Thread-42                    org.geppetto.simulator.remote.services.NSGSimulatorService        Error executing job in remote server 
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                        Exception in thread "Thread-42" java.lang.RuntimeException: org.geppetto.core.common.GeppettoExecutionException: Error executing simulation for Neuron NSG Simulator Service: Error executing job 
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                         at org.geppetto.simulation.manager.SimulatorRunThread.run(SimulatorRunThread.java:42) 
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                        Caused by: org.geppetto.core.common.GeppettoExecutionException: Error executing simulation for Neuron NSG Simulator Service: Error executing job                                                                                                                                                                                                              
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                         at org.geppetto.simulator.remote.services.NSGSimulatorService.simulate(NSGSimulatorService.java:209)          
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                         at org.geppetto.simulation.manager.SimulatorRunThread.run(SimulatorRunThread.java:37)                         
[2017-12-18 13:41:45.201] ERROR Thread-42                    System.err                                                        Caused by: org.geppetto.core.common.GeppettoExecutionException: Error executing job                            
[2017-12-18 13:41:45.202] ERROR Thread-42                    System.err                                                         at org.geppetto.simulator.remote.services.NSGSimulatorService.simulate(NSGSimulatorService.java:166)          
[2017-12-18 13:41:45.202] ERROR Thread-42                    System.err                                                         ... 1 more                                                                                                    
```

**Comment by pgleeson** [comment]
Done & stable
